### PR TITLE
chore(github): Updates pull request template

### PR DESCRIPTION
**Pull request by talend-glorieux**
* Removes pull request type section. That information is redundant of the
pull request title. Adds deletion notice.
* Removes pull request requirements checkboxes. Those should only be
used to mark remaining tasks/todos on a given pull request.
* Removes pull request breaking change checkboxes. Now asks for the
section to be removed if the pull request doesn't contain any breaking change.

### CODE REVIEW

**Comment by sgandon** [comment]
I agree with this PR but there is no document stating how the PR shall be named (the title you mentioned), it is assumed to be identical to a commit message but I can't find anywhere this is written.

**Comment by talend-glorieux** [comment]
@sgandon Good point! I'll update the documents.

**Comment by talend-glorieux** [comment]
@sgandon Do you think the addition is sufficient?

**Comment by sgandon** [comment]
yep that is fine by me.

**Comment by talend-glorieux** [comment]
@jmfrancois Is it better now?

**Pull request merged**
