### PR TITLE
chore(github): Remove checkbox from title

### PR DESCRIPTION
**Pull request by talend-glorieux**
In markdown checkboxes can't be added to bold text.
I've removed the checkbox and added a comment to remove the breaking change block if not required.

### CODE REVIEW

**Comment by sgandon** [comment]
I agree with marco, so I would suggest to just remove the bold tags only.

**Comment by talend-glorieux** [comment]
@mbuccini @sgandon 
Yep agree with you on the removal part.
I reverted what I did to only bold the text part.

**Comment by mbuccini** [comment]
@talend-glorieux looks much better! Would it be possible to set it at the beginning of the line? Right now, it seems it's belonging to the above list of checkboxes. :)

**Comment by talend-glorieux** [comment]
@mbuccini I don't see what you mean by `beginning of the line`.

**Comment by talend-glorieux** [comment]
@mbuccini Any update?

**Comment by sgandon** [comment]
I think Marco means removing the leading space before the brackets. I am ok with the suggestion.

**Comment by talend-glorieux** [comment]
Closing due to inactivity.

**Pull request closed without merging**
