### PR TITLE
Set indent to 4 spaces

### PR DESCRIPTION
**Pull request by jsomsanith**

### CODE REVIEW

**Comment by talend-glorieux** [comment]
What's the status of that discussion?

**Comment by jsomsanith** [comment]
Your argument on Tab over spaces is very good. Let's switch to tab.

**Comment by talend-glorieux** [comment]
@jsomsanith Are you sure? 
Only 2/3 people expressed there point of views.
I'd like to have the other frontend devs give there opinions before jumping to conclusions ;)

@Talend/frontend Could you guys give a quick opinion here ?

**Comment by talend-sromain** [comment]
I agree on tabs because everyone can set the visual aspect of a tab as they like it the most.

**Comment by talend-glorieux** [comment]
Looks like most of the frontend devs don't have opinions on the matter.
@jsomsanith If that's OK with you let's go forward with the tabs.

**Comment by acateland** [comment]
So can we set a decision in stone about this ?
I really don't care, about either choice but i care about a choice being made.

**Comment by jmfrancois** [comment]
Ok for tabs except for package.json because NPM do two spaces

**Pull request merged**
